language: scala
scala:
  - 2.9.1
jdk:
  - oraclejdk7
before_script:
  - createuser -P partake -U postgres --no-superuser --no-createdb --no-createrole partake
  - createdb -U postgres -O partake --no-password partake-test
