language: scala
scala:
  - 2.9.1
jdk:
  - oraclejdk7
before_script:
  - createuser -U postgres --no-superuser --no-createdb --no-createrole --no-password partake
  - createdb -U postgres -O partake --no-password partake-test
