language: scala
scala:
  - 2.9.1
jdk:
  - oraclejdk7
notifications:
  email:
    recipients:
      - partake-dev@googlegroups.com
before_script:
  - createuser partake -P partake -U postgres --no-superuser --no-createdb --no-createrole
  - createdb partake-test -U postgres -O partake --no-password
